# Use postgres/example user/password credentials with data in same folder
version: '3.1'

services:
  api:
    image: cronpupapi
    ports:
      - 3001:3001
    restart: always
    volumes:
       - ./static:/app/static


